#!/bin/bash
set -e

if [ "$1" = 'qgis' ]; then

	# Render the files directory writable from Apache.
	dir=/fileport/qgisfiles
	mkdir -p "$dir"
	chown -R www-data "$dir"

	# Ensure Qt network disk cache is writable for the www-data workers.
	mkdir -p /var/cache/qgis
	chown www-data:www-data /var/cache/qgis

	# run the QGIS Server
	exec start-server
fi

exec "$@"
